# KorG's nickname
player_nickname = KorG

# Server definitions
level_height = 128
level_width = 256

# Keybindings
key_exit = q

# Layout settings

win_stdscr_large_y = 0
win_stdscr_large_x = 0
win_stdscr_large_max_y = 0
win_stdscr_large_max_x = 0
win_stdscr_state = 2

win_area_large_y = 2
win_area_large_x = 0
win_area_large_max_y = -2
win_area_large_max_x = 0
win_area_state = 2

win_chat_small_y = 0
win_chat_small_x = -30
win_chat_small_x_ispercent = 1
win_chat_small_max_y = 2
win_chat_small_max_x = 30
win_chat_small_max_x_ispercent = 1
win_chat_state = 1

win_inventory_large_y = 0
win_inventory_large_x = 0
win_inventory_large_max_y = 0
win_inventory_large_max_x = 0
win_inventory_state = 0

win_map_large_y = 0
win_map_large_x = 0
win_map_large_max_y = 0
win_map_large_max_x = 0
win_map_state = 0

win_status_large_y = -2
win_status_large_x = 0
win_status_large_max_y = 2
win_status_large_max_x = 0
win_status_state = 2

win_sysmsg_small_y = 0
win_sysmsg_small_x = 0
win_sysmsg_small_max_y = 2
win_sysmsg_small_max_x = 70
win_sysmsg_small_max_x_ispercent = 1
win_sysmsg_state = 1
