win_stdscr_y = 0
win_stdscr_x = 0
win_stdscr_max_y = 0
win_stdscr_max_x = 0
win_stdscr_state = 2

win_area_y = 0
win_area_x = 0
win_area_max_y = 10
win_area_max_x = 10
win_area_state = 2

win_chat_y = 0
win_chat_x = 50
win_chat_max_y = 2
win_chat_max_x = 30
win_chat_state = 1

win_inventory_y = 0
win_inventory_x = 0
win_inventory_max_y = 0
win_inventory_max_x = 0
win_inventory_state = 0

win_map_y = 0
win_map_x = 0
win_map_max_y = 0
win_map_max_x = 0
win_map_state = 0

win_status_y = 23
win_status_x = 0
win_status_max_y = 2
win_status_max_x = 0
win_status_state = 2

win_sysmsg_y = 0
win_sysmsg_x = 0
win_sysmsg_max_y = 2
win_sysmsg_max_x = 50
win_sysmsg_state = 2
